### ISSUE TITLE
game.tscn - scene is defect

### ISSUE THREAD

**Issue by ds2k5** [DeStout/Godot_JetBikes#1]
Hello,
load the code and open in Godot 3.2.3 got this error:

![Screen Capture_select-area_20201204204119](https://user-images.githubusercontent.com/11292286/101208022-d8b6e000-3671-11eb-979a-b0111e5ac219.png)

How to fix this ?

**Comment by DeStout** [comment]
I'm not sure about this. I downloaded the repository into 3.3.2 and it worked right off the bat.
